
spring:
  profiles:
    active:
      - local
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: web
  mail:
    host: smtp.gmail.com
    port:  587
    protocol: smtp
    default-encoding: UTF-8
    username: addvalues2@gmail.com
    password: 
    smtp:
      start-tls-enable: true
      auth: true
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 1234
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
